# Generated by Django 3.2.9 on 2021-11-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tecqnique',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (0, 'Single Choice')], default=0, verbose_name='Type of Qustion'),
        ),
    ]
