# Generated by Django 3.2.9 on 2021-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'fundamental'), (1, 'easy'), (2, 'intermediate'), (3, 'hard'), (4, 'extremely hard')], default=0, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tecqnique',
            field=models.IntegerField(choices=[(0, 'Multiple Choice')], default=0, verbose_name='Type of Qustion'),
        ),
    ]
